version: "3"
services:
  node-app:
    container_name: node-app-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "3000:3000"
    environment:
      - PORT=3000 
      - NODE_ENV= production
      
