version: "3"
services:
  node-app:
    volumes:
      - ./src:/app/src:ro
    build: 
      context: .
      target: development
    environment:
      - NODE_ENV= development
    command: npm run start-dev
      
