version: "3"
services:
  node-app:
    container_name: node-app-container
    image: amrmohamedatef/repo1
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
      
  nginx:
    image: nginx:alpine-slim
    volumes:
     - ./templates:/etc/nginx/templates
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "7070:80"
    depends_on:
      - node-app
